import { createServerSupabaseClient } from "@/lib/supabase";
import { Calculator, Mail, Calendar, Coins, ExternalLink } from "lucide-react";

export const metadata = {
  title: "Estimator Submissions | Admin",
};

export const revalidate = 0;

export default async function EstimatorSubmissionsPage() {
  const supabase = createServerSupabaseClient();
  let submissions: any[] = [];
  
  if (supabase) {
    const { data } = await supabase
      .from('estimator_submissions')
      .select('*')
      .order('created_at', { ascending: false });
    submissions = data || [];
  }

  function formatCurrency(amount: number, currency: string) {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: currency || 'INR',
      maximumFractionDigits: 0,
    }).format(amount);
  }

  return (
    <div className="p-8">
      <div className="mb-8 flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-heading font-bold text-gray-900 dark:text-white">Estimator Leads</h1>
          <p className="text-gray-500 dark:text-gray-400 mt-1">Review project estimates and leads generated by the configurator.</p>
        </div>
        <div className="bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-400 px-4 py-2 rounded-xl font-medium text-sm">
          {submissions.length} Total Leads
        </div>
      </div>

      {!supabase ? (
        <div className="p-12 text-center bg-white dark:bg-[#111827] rounded-3xl border border-gray-200 dark:border-gray-800">
          Supabase not configured.
        </div>
      ) : submissions.length === 0 ? (
        <div className="p-12 text-center bg-white dark:bg-[#111827] rounded-3xl border border-gray-200 dark:border-gray-800 text-gray-500">
          No estimator submissions yet.
        </div>
      ) : (
        <div className="space-y-6">
          {submissions.map((sub) => (
            <div key={sub.id} className="bg-white dark:bg-[#111827] rounded-3xl border border-gray-200 dark:border-gray-800 overflow-hidden shadow-sm hover:border-blue-500/30 transition-colors">
              <div className="p-6 md:p-8">
                <div className="flex flex-col md:flex-row justify-between items-start gap-6 mb-8">
                  <div className="flex-1">
                    <div className="flex items-center gap-3 mb-2">
                      <h3 className="text-2xl font-bold text-gray-900 dark:text-white">{sub.name || 'Anonymous Lead'}</h3>
                      <span className="text-xs bg-blue-50 dark:bg-blue-500/10 text-blue-600 dark:text-blue-400 px-3 py-1 rounded-full font-bold uppercase tracking-wider">
                        {sub.project_type}
                      </span>
                    </div>
                    <div className="flex flex-wrap gap-4 text-sm text-gray-500">
                      <a href={`mailto:${sub.email}`} className="flex items-center gap-2 hover:text-blue-600 transition-colors">
                        <Mail className="w-4 h-4" /> {sub.email || 'No email provided'}
                      </a>
                      <div className="flex items-center gap-2">
                        <Calendar className="w-4 h-4" /> {new Date(sub.created_at).toLocaleDateString()}
                      </div>
                    </div>
                  </div>
                  <div className="text-right">
                    <div className="text-sm text-gray-500 uppercase tracking-widest font-bold mb-1">Estimate Range</div>
                    <div className="text-3xl font-heading font-bold text-blue-600 dark:text-blue-400">
                      {formatCurrency(sub.estimated_min, sub.currency)} – {formatCurrency(sub.estimated_max, sub.currency)}
                    </div>
                  </div>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8">
                  <div className="p-4 bg-gray-50 dark:bg-[#0f131d] rounded-2xl border border-gray-100 dark:border-gray-800">
                    <div className="text-[10px] text-gray-500 uppercase tracking-widest font-bold mb-2">Design Quality</div>
                    <div className="text-sm font-semibold text-gray-900 dark:text-white">{sub.design_quality}</div>
                  </div>
                  <div className="p-4 bg-gray-50 dark:bg-[#0f131d] rounded-2xl border border-gray-100 dark:border-gray-800">
                    <div className="text-[10px] text-gray-500 uppercase tracking-widest font-bold mb-2">Timeline</div>
                    <div className="text-sm font-semibold text-gray-900 dark:text-white">{sub.timeline}</div>
                  </div>
                  <div className="p-4 bg-gray-50 dark:bg-[#0f131d] rounded-2xl border border-gray-100 dark:border-gray-800">
                    <div className="text-[10px] text-gray-500 uppercase tracking-widest font-bold mb-2">Support Plan</div>
                    <div className="text-sm font-semibold text-gray-900 dark:text-white">{sub.support}</div>
                  </div>
                  <div className="p-4 bg-gray-50 dark:bg-[#0f131d] rounded-2xl border border-gray-100 dark:border-gray-800">
                    <div className="text-[10px] text-gray-500 uppercase tracking-widest font-bold mb-2">Currency</div>
                    <div className="text-sm font-semibold text-gray-900 dark:text-white">{sub.currency}</div>
                  </div>
                </div>

                <div>
                  <div className="text-[10px] text-gray-500 uppercase tracking-widest font-bold mb-3">Selected Features</div>
                  <div className="flex flex-wrap gap-2">
                    {Array.isArray(sub.features) && sub.features.map((f: string) => (
                      <span key={f} className="px-3 py-1.5 bg-gray-100 dark:bg-gray-800 text-gray-700 dark:text-gray-300 rounded-xl text-xs font-medium">
                        {f}
                      </span>
                    ))}
                    {(!sub.features || sub.features.length === 0) && <span className="text-sm text-gray-400">No extra features selected</span>}
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
